BuscaSemantica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name='index'),
    path('controll/', views.controll, name='controll'),
    path('documents/', include('documents.urls'), name='documents'),
    path('', include('search.urls'), name='search'),
    path('user/', include('users.urls'), name='users'),
    
    path('reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_confirm.html", success_url= "/user/reset_password_complete/", ), name="password_reset_confirm"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_user, name='signup'),
    path('reset_password/', 
         auth_views.PasswordResetView.as_view(  template_name="users/password_reset.html", 
                                                success_url= "/user/reset_password_done/",
                                                email_template_name = "users/password_reset_email.html",
                                                subject_template_name= "users/password_reset_subject.txt",), 
                                                name="reset_password", ),

    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_done.html"), name="password_reset_done"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_complete.html"), name="password_reset_complete"),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import send_mail

# Create your views here.
def login_user(request):
    
    if request.user.is_authenticated:
        return redirect("index")

    if request.POST:
        user = authenticate(username= request.POST.get("username", ""), password= request.POST.get("password", ""))

        if user is not None:
            login(request, user)
            return redirect("search:index")
        else:
            return render(request, 'users/login.html', {'Error': 'Usuário ou senha inválido!'})

    return render(request, 'users/login.html')

@login_required(redirect_field_name="users:login")
def logout_user(request):

    if request.POST:
        logout(request)
        return redirect("search:index")

    return render(request, 'users/logout.html')

def signup_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = User.objects.filter(username=username).first()
        email_v = User.objects.filter(email=email).first()

        if user:
            return render(request, 'users/signup.html', {'Error': 'Já existe um usuário com esse nome.'})
        if email_v:
            return render(request, 'users/signup.html', {'Error': 'Já existe um usuário com esse email.'})
        
        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()
        return redirect("users:login")

    else:
        return render(request, 'users/signup.html')

def password_user(request):
    return render(request, 'users/password_reset.html')

users/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DataResearch</title>
        <!-- Favicon-->
        <!-- <link rel="icon" type="image/x-icon" href="assets/favicon.ico" /> -->
        <!-- Custom Google font-->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'BuscaSemantica/css/style.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href="/">
                        <img class="img-fluid" src="{% static 'BuscaSemantica/assets/logo_2.png' %}" alt="..." />
                        <span class="fw-bolder text-gradient">DataResearch</span>
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Contact form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 mb-3"><i class="bi bi-people"></i></div>
                            <h1 class="fw-bolder">Seja bem vindo</h1>
                            <p class="lead fw-normal text-muted mb-0">Vamos organizar juntos!</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
                            <div class="col-lg-8 col-xl-6">
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- * * SB Forms Contact Form * *-->
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- This form is pre-integrated with SB Forms.-->
                                <!-- To make this form functional, sign up at-->
                                <!-- https://startbootstrap.com/solution/contact-forms-->
                                <!-- to get an API token!-->
                                <form id="contactForm" method='POST' autocomplete="off" action="{% url 'users:login' %}" >
                                    {% csrf_token %}
                                    <!-- Name input-->
                                    <div class="form-floating mb-3">
                                        <input autocomplete="false" name="username" class="form-control" id="name" type="text" placeholder="Digite seu nome de usuário" required />
                                        <label for="name">Nome de Usuário</label>
                                        <div class="invalid-feedback" data-sb-feedback="name:required">A nome de usuário é obrigatório.</div>
                                    </div>
                                    <!-- Password input-->
                                    <div class="form-floating mb-3">
                                        <input autocomplete="false" name='password' class="form-control" id="email" type="password" placeholder="Digite sua Senha" data-sb-validations="required" />
                                        <label for="email">Senha</label>
                                        <div class="invalid-feedback" data-sb-feedback="email:required">A senha é obrigatório.</div>
                                    </div>
                                    <!-- Esqueci minha senha -->
                                    <div class="form-floating mb-3">
                                        <p class="form-check mb-0">
                                        <a href="{% url 'users:reset_password' %}" class="text-body">Esqueci minha senha</a>
                                    </p>
                                    </div>
                                    <!-- Submit success message-->
                                    <!---->
                                    <!-- This is what your users will see when the form-->
                                    <!-- has successfully submitted-->
                                    <div class="d-none" id="submitSuccessMessage">
                                        <div class="text-center mb-3">
                                            <div class="fw-bolder">Form submission successful!</div>
                                            To activate this form, sign up at
                                            <br />
                                            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                        </div>
                                    </div>
                                    <!-- Submit error message-->
                                    <!---->
                                    <!-- This is what your users will see when there is-->
                                    <!-- an error submitting the form-->
                                    {% if Error %}<div id="submitErrorMessage"><div class="text-center text-danger mb-3">{{Error}}</div></div>{% endif %}
                                    <!-- Submit Button-->
                                    <div class="d-flex">
                                        <button class="btn btn-primary btn-lg w-100" style="margin-right:10px" id="submitButton" type="submit">Entrar</button>
                                        <a class="btn btn-outline-dark btn-lg px-5 py-3 fs-6 fw-bolder w-100" style="margin-left:10px"  href="{% url 'users:signup' %}">Criar conta</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">Copyright &copy; DataResearch 2023</div></div>
                    <div class="col-auto">
                        <!-- <a class="small" href="#!">Privacy</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="#!">Terms</a>
                        <span class="mx-1">&middot;</span> -->
                        <!-- <a class="small" href="#!">Contatos</a> -->
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'BuscaSemantica/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <!-- <script src="js/scripts.js"></script> -->
    </body>
</html>

users/templates/users/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DataResearch</title>
        <!-- Favicon-->
        <!-- <link rel="icon" type="image/x-icon" href="assets/favicon.ico" /> -->
        <!-- Custom Google font-->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'BuscaSemantica/css/style.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href="index.html"><span class="fw-bolder text-primary">DataResearch</span></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Contact form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 mb-3"><i class="bi bi-door-open"></i></div>
                            <h1 class="fw-bolder">Saindo</h1>
                            <p class="lead fw-normal text-muted mb-0">Obrigado por usar nosso sistema!</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
                            <div class="col-lg-8 col-xl-6">
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- * * SB Forms Contact Form * *-->
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- This form is pre-integrated with SB Forms.-->
                                <!-- To make this form functional, sign up at-->
                                <!-- https://startbootstrap.com/solution/contact-forms-->
                                <!-- to get an API token!-->
                                <form id="contactForm" method='POST' autocomplete="off" action="{% url 'users:logout' %}" >
                                    {% csrf_token %}
                                    <!-- Submit error message-->
                                    <div class="d-flex">
                                        <button class="btn btn-primary btn-lg w-100" style="margin-right:10px" id="submitButton" type="submit">Sair</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">Copyright &copy; DataResearch 2023</div></div>
                    <div class="col-auto">
                        <!-- <a class="small" href="#!">Privacy</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="#!">Terms</a>
                        <span class="mx-1">&middot;</span> -->
                        <!-- <a class="small" href="#!">Contatos</a> -->
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'BuscaSemantica/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <!-- <script src="js/scripts.js"></script> -->
    </body>
</html>

users/templates/users/password_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DataResearch</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'BuscaSemantica/css/style.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href="/">
                        <img class="img-fluid" src="{% static 'BuscaSemantica/assets/logo_2.png' %}" alt="..." />
                        <span class="fw-bolder text-gradient">DataResearch</span>
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Contact form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 mb-3"><i class="bi bi-people"></i></div>
                            <h1 class="fw-bolder">Redefinição de senha concluída</h1>
                        </div>
                        <div class="row gx-5 justify-content-center">
                            <div class="col-lg-8 col-xl-6">
                                <p class="lead fw-normal text-muted text-center mb-0">
                                    Sua nova senha foi salva com sucesso. Volte para a página de login para entrar na ferramenta.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">Copyright &copy; DataResearch 2023</div></div>
                    <div class="col-auto">
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'BuscaSemantica/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <!-- <script src="js/scripts.js"></script> -->
    </body>
</html>

users/templates/users/password_reset_email.html
{% autoescape off %}
Para iniciar o processo de redefinição de senha para sua conta no DataResearch, clique no link abaixo:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Se o link não funcionar ao clicar, por favor tente copiar e colar a URL em uma nova guia do navegador.

Atenciosamente,
Equipe DataResearch
{% endautoescape %}

users/templates/users/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DataResearch</title>
        <!-- Custom Google font-->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'BuscaSemantica/css/style.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href="/">
                        <img class="img-fluid" src="{% static 'BuscaSemantica/assets/logo_2.png' %}" alt="..." />
                        <span class="fw-bolder text-gradient">DataResearch</span>
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Contact form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 mb-3"><i class="bi bi-people"></i></div>
                            <h1 class="fw-bolder">Seja bem vindo</h1>
                            <p class="lead fw-normal text-muted mb-0">Vamos organizar juntos!</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
                            <div class="col-lg-8 col-xl-6">
                                <form id="contactForm" method='POST' autocomplete="off" action="{% url 'users:signup' %}" >
                                    {% csrf_token %}
                                    <!-- Name input-->
                                    <div class="form-floating mb-3">
                                        <input autocomplete="false" name="username" class="form-control" id="name" type="text" placeholder="Digite seu nome de usuário" required />
                                        <label for="name">Nome de Usuário</label>
                                        <div class="invalid-feedback" data-sb-feedback="name:required">A nome de usuário é obrigatório.</div>
                                    </div>
                                    <!-- Email input-->
                                    <div class="form-floating mb-3">
                                        <input autocomplete="false" name="email" class="form-control" id="email" type="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" placeholder="Digite seu e-mail" required />
                                        <label for="email">E-mail</label>
                                        <div class="invalid-feedback" data-sb-feedback="email:required">O endereço de e-mail é obrigatório.</div>
                                    </div>
                                    <!-- Password input-->
                                    <div class="form-floating mb-3">
                                        <input autocomplete="false" name='password' class="form-control" id="password" type="password" placeholder="Digite sua senha" data-sb-validations="required" />
                                        <label for="password">Senha</label>
                                        <div class="invalid-feedback" data-sb-feedback="password:required">A senha é obrigatório.</div>
                                    </div>
                                    <!-- Submit success message-->
                                    <div class="d-none" id="submitSuccessMessage">
                                        <div class="text-center mb-3">
                                            <div class="fw-bolder">Form submission successful!</div>
                                            To activate this form, sign up at
                                            <br />
                                            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                        </div>
                                    </div>
                                    <!-- Submit error message-->
                                    {% if Error %}<div id="submitErrorMessage"><div class="text-center text-danger mb-3">{{Error}}</div></div>{% endif %}
                                    <!-- Submit Button-->
                                    <div class="d-flex">
                                        <button class="btn btn-primary btn-lg w-100" style="margin-right:10px" id="submitButton" type="submit">Cadastrar</button>
                                        <a class="btn btn-outline-dark btn-lg px-5 py-3 fs-6 fw-bolder w-100" style="margin-left:10px"  href="{% url 'users:login' %}">Voltar ao login</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">Copyright &copy; DataResearch 2023</div></div>
                    <div class="col-auto">
                        <!-- <a class="small" href="#!">Privacy</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="#!">Terms</a>
                        <span class="mx-1">&middot;</span> -->
                        <!-- <a class="small" href="#!">Contatos</a> -->
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'BuscaSemantica/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <!-- <script src="js/scripts.js"></script> -->
    </body>
</html>