BuscaSemantica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name='index'),
    path('controll/', views.controll, name='controll'),
    path('documents/', include('documents.urls'), name='documents'),
    path('', include('search.urls'), name='search'),
    path('user/', include('users.urls'), name='users'),
    
    path('reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_confirm.html", success_url= "/user/reset_password_complete/", ), name="password_reset_confirm"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documents/urls.py
from django.urls import path
from . import views

app_name = "documents"
urlpatterns = [
    path('', views.document_list, name='list'),
    path('add/', views.document_add_edit, name='add'),
    path('edit/<int:pk>', views.document_add_edit, name='edit'),
    path('delete/<int:pk>', views.document_delete, name='delete'),
    path('folder/', views.folder_add_edit, name='add_folder'),
    path('folder/<int:pk>', views.folder_add_edit, name='edit_folder'),
    path('delete_folder/<int:pk>', views.delete_folder, name='delete_folder'),
    # path('register/', views.material_add, name='material_add'),
    # path('list/', views.material_list, name='material_list'),
    # path('register/', views.material_register, { 'pk': None}, name='material_register'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_user, name='signup'),
    path('reset_password/', 
         auth_views.PasswordResetView.as_view(  template_name="users/password_reset.html", 
                                                success_url= "/user/reset_password_done/",
                                                email_template_name = "users/password_reset_email.html",
                                                subject_template_name= "users/password_reset_subject.txt",), 
                                                name="reset_password", ),

    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_done.html"), name="password_reset_done"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_complete.html"), name="password_reset_complete"),
]

BuscaSemantica/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from search import tests  
from django.urls import reverse

def about(request):
    return render(request, "BuscaSemantica/about.html")

def controll(request):
    return render(request, "BuscaSemantica/controll.html")

def reset_password(request, uid, token):
    print(uid)
    print(token)
    return render(request, 'users/password_confirm.html')

BuscaSemantica/templates/BuscaSemantica/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DataResearch</title>
        <!-- Favicon-->
        <!-- <link rel="icon" type="image/x-icon" href="BuscaSemantica/assets/artificial-intelligence.png" /> -->
        <!-- Custom Google font-->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'BuscaSemantica/css/style.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-white py-3 ">
            <div class="container px-5">
                
                <a class="navbar-brand" href="/">
                    <img class="img-fluid" src="{% static 'BuscaSemantica/assets/logo_2.png' %}" alt="..." />
                    <span class="fw-bolder text-gradient">DataResearch</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                        {% if user.is_authenticated %}
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'documents:list' %}">
                                Gerenciar documentos
                            </a>
                        </li>	
                        {% endif %}
                        <li class="nav-item"><a class="nav-link" href="/">Página inicial</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% if user.is_authenticated %}/about/{% endif %}#about">Sobre</a></li>
                        {% if not user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Entrar</a></li>
                        {% else %}
                        <li class="nav-item dropdown">
                            
                            <a class="nav-link bi-person-circle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                {{user.get_username}}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                              <li><a class="dropdown-item" type="button" href="{% url 'users:logout' %}">Sair</a></li>
                            </ul>
                          
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <main class="flex-shrink-0" style="height: calc(100% - 144px);">
            
            {% block content %}
			
			{% endblock%}
        </main>
        <!-- Footer-->
        <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">Copyright &copy; DataResearch 2023</div></div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'BuscaSemantica/js/bootstrap.bundle.min.js' %}"></script>
        {% if user.is_authenticated %}
        <script src="{% static 'BuscaSemantica/js/service.js' %}"></script>

        {% if request.resolver_match.app_name == 'documents' %}

        <script src="{% static 'BuscaSemantica/js/file-controll.js' %}"></script>
        <script src="{% static 'BuscaSemantica/js/folder-controll.js' %}"></script>
        <script>
            window.FolderTree = new FolderTree( document.querySelector('#folder-tree'), document.querySelector('#folder-filter'));
            window.FileForm = new FileForm( document.querySelector('#form_document'));
        </script>

        {% elif request.resolver_match.app_name == 'search' %}
        <script src="{% static 'BuscaSemantica/js/search-controll.js' %}"></script>
        <script>
            window.Search = new Search( document.querySelector('#search-filter'), document.querySelector('#result-list'));
        </script>

        {% endif %}
        
        <div class="modal-backdrop show d-none align-items-center d-flex justify-content-center" id="loader-service" style="z-index: 9999;">
            <div class="spinner-border text-light p-5 align-items-center d-flex" style="width: 100px; height: 100px; font-size: 4rem;" role="status">
                <i class="ml-1 bi"></i>
            </div>
        </div>
        <script src="{% static 'BuscaSemantica/js/script.js' %}"></script>
        {% endif %}
        <div class="modal" tabindex="-1" id="errors-message">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <form method="POST" {% if form and form.instance.id %}action="{% url 'documents:delete' form.instance.id %}" {% endif%}>
                        {% csrf_token %}
                        <div class="modal-header">
                            <h5 class="modal-title text-danger"><i class="bi bi-exclamation-circle mx-1"></i>Aviso de erro</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
                        </div>
                                
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

BuscaSemantica/templates/BuscaSemantica/controll.html
{% extends "BuscaSemantica/base.html" %}
{% block content %}
<div class="container">
    
</div>
{% endblock %}