BuscaSemantica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name='index'),
    path('controll/', views.controll, name='controll'),
    path('documents/', include('documents.urls'), name='documents'),
    path('', include('search.urls'), name='search'),
    path('user/', include('users.urls'), name='users'),
    
    path('reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_confirm.html", success_url= "/user/reset_password_complete/", ), name="password_reset_confirm"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documents/urls.py
from django.urls import path
from . import views

app_name = "documents"
urlpatterns = [
    path('', views.document_list, name='list'),
    path('add/', views.document_add_edit, name='add'),
    path('edit/<int:pk>', views.document_add_edit, name='edit'),
    path('delete/<int:pk>', views.document_delete, name='delete'),
    path('folder/', views.folder_add_edit, name='add_folder'),
    path('folder/<int:pk>', views.folder_add_edit, name='edit_folder'),
    path('delete_folder/<int:pk>', views.delete_folder, name='delete_folder'),
    # path('register/', views.material_add, name='material_add'),
    # path('list/', views.material_list, name='material_list'),
    # path('register/', views.material_register, { 'pk': None}, name='material_register'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_user, name='signup'),
    path('reset_password/', 
         auth_views.PasswordResetView.as_view(  template_name="users/password_reset.html", 
                                                success_url= "/user/reset_password_done/",
                                                email_template_name = "users/password_reset_email.html",
                                                subject_template_name= "users/password_reset_subject.txt",), 
                                                name="reset_password", ),

    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_done.html"), name="password_reset_done"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_complete.html"), name="password_reset_complete"),
]

documents/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.fields.files import FieldFile
import os


# Create your models here.
class Folder(models.Model):
    id = models.AutoField(verbose_name="Sequência", primary_key=True, auto_created=True)
    name = models.CharField(verbose_name='Nome', max_length=50)
    id_parent_dir = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name
    
    def create_folder_tree():
        
        def get_child(parent):
            children = Folder.objects.all().filter(id_parent_dir=parent['id'])
            for child in children:
                if ('children' not in parent):
                    parent['children'] = []
                parent['children'].append(get_child({'id': child.id, 'name': child.name, 'parent': parent['id']}))
                
            return parent
        directories = Folder.objects.all().filter(id_parent_dir=None)
        dirTree = []
        for dir in directories:
            dirTree.append(get_child({'id': dir.id, 'name': dir.name, 'parent': None}))
        
        return dirTree

class File(models.Model):
    
    def file_directory_path(instance, filename):

        return f"{instance.user_created}/{filename}"

    id = models.AutoField(verbose_name="Seq.", primary_key=True, auto_created=True)
    name = models.CharField(verbose_name='Nome', max_length=255)
    file = models.FileField(verbose_name='Arquivo', upload_to=file_directory_path)
    description = models.TextField(verbose_name='Descrição', max_length=255)
    id_folder = models.ForeignKey(Folder, on_delete=models.PROTECT, verbose_name='Pasta', related_name='pasta')

    # Audit
    dt_created = models.DateTimeField(verbose_name='Data de criação', auto_now_add=True, null=True)
    dt_updated = models.DateTimeField(verbose_name='Data de atualização', auto_now=True, null=True)
    user_created = models.ForeignKey(User, on_delete= models.CASCADE, verbose_name='Criado por: ', related_name='usuario_criacao', null=True)
    user_updated = models.ForeignKey(User, on_delete= models.CASCADE, verbose_name='Atualizado por: ', related_name='usuario_atualizacao', null=True)
    
    def __str__(self):
        return self.name
    
    def filename(self):
        if not self.file or not os.path.isfile(self.file.path):
            return None
        return os.path.basename(self.file.name)
    
    def getColumnsToGrid():
        fields = ['id','name', 'description', 'id_folder', 'file']
        newList = [ {'attname': column, 'verbose_name': str(getattr(File,column).field._verbose_name)} for column in fields if hasattr(File, column)]
        return newList
    
    def to_json(self):
        fields = ['id','name', 'description', 'id_folder', 'file', 'dt_created', 'user_created']
        data = {}
        for column in fields:
            if hasattr(File, column):
                value = getattr(self,column)
                if (isinstance(value, Folder)):
                    data[column] = value.name
                elif (isinstance(value, FieldFile)):
                    data[column] = value.name
                elif (isinstance(value, User)):
                    data[column] = value.username
                else:
                    data[column] = value
        return data
    
        
@receiver(models.signals.post_delete, sender=File)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)

@receiver(models.signals.pre_save, sender=File)
def auto_delete_file_on_change(sender, instance, **kwargs):
    if not instance.pk :
        return False
    
    old_instance = File.objects.get(pk=instance.pk)

    if not old_instance.file:
        return False
    
    if not old_instance.file == instance.file:
        if os.path.isfile(old_instance.file.path):
            os.remove(old_instance.file.path)

documents/forms.py
from django import forms
from .models import Folder, File

class FolderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(FolderForm, self).__init__(*args, **kwargs)
        self.fields['id_parent_dir'].queryset = Folder.objects.exclude(id=self.instance.pk)

    id = forms.CharField(max_length=255, widget=forms.HiddenInput(), required=False)
    name = forms.CharField(label='Nome', max_length=255)
    id_parent_dir = forms.ModelChoiceField(queryset=Folder.objects.all())

    class Meta:
        model = Folder
        exclude = []

class FileForm(forms.ModelForm ):
    id = forms.CharField(max_length=255, widget=forms.HiddenInput(), required=False)
    name = forms.CharField(label='Nome', max_length=255)
    description = forms.CharField(label='Descrição', max_length=255, widget= forms.Textarea(attrs={'rows':5}))
    file = forms.FileField(label='Arquivo', required=False)
    id_folder = forms.ModelChoiceField(queryset=Folder.objects.all())


    class Meta:
        model = File
        exclude = ['dt_created', 'dt_updated', 'user_created', 'user_updated']
        
    field_order = ['id','name', 'description', 'id_folder', 'file']

documents/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Folder, File
from .forms import FileForm, FolderForm
from rest_framework.decorators import api_view
from django.http import JsonResponse
from BuscaSemantica.openIAService import OpenIAService
from django.db.models.deletion import ProtectedError
import os


@login_required(redirect_field_name="users:login")
def document_list(request):
    metadata = {
        'columns': File.getColumnsToGrid(),
        'content': File.objects.all()
    }
    return render(request, 'documents/list.html', {'metadata' : metadata,'formFolder': FolderForm(),'folders': Folder.create_folder_tree(), 'folders_list' : Folder.objects.all()})


@login_required(redirect_field_name="users:login")
def document_add_edit(request, pk = None):
    if request.POST or request.FILES:
        result = {
            'saved': False
        }
        if (pk is None):
            form = FileForm(data = request.POST)
        else: 
            documentModel = get_object_or_404(File, pk=pk)
            form = FileForm(data = request.POST, instance= documentModel)
        if (form.is_valid()):
            try:
                document = form.save(commit=False)
                if (request.POST.get('delete_file') == 'true'):
                    if document.file:
                        if os.path.isfile(document.file.path):
                            os.remove(document.file.path)
                            document.file = None

                filepath = request.FILES.get('file', False)
                if (filepath):
                    if (not filepath.name.upper().endswith('PDF')):
                        result['error'] = 'O arquivo não é um PDF.'
                        return JsonResponse(result)
                    document.file = filepath

                if (document.pk):
                    document.user_updated = request.user
                else:
                    document.user_created = request.user
                document.save()
                OpenIAService().appendInstance(document)
                if (filepath):
                    OpenIAService().appendFile(document)
                result['saved'] = True
            except Exception as a:
                result['error'] = str(a)
            return JsonResponse(result)
    else:
        if (pk is None):
            form = FileForm()
            setattr(form, 'form_url', '/documents/add/')
            setattr(form, 'form_title', 'Adicionar documento ')
        else:
            documentModel = get_object_or_404(File, pk=pk)
            form = FileForm(instance = documentModel)
            setattr(form, 'form_url', f'/documents/edit/{pk}')
            setattr(form, 'form_title', 'Editar documento ')
    return render(request, "documents/add_edit.html", {"form": form, 'folders': Folder.create_folder_tree(), 'folders_list' : Folder.objects.all()})   

@login_required()
@api_view(('POST',))
def folder_add_edit(request, pk = None):

    folder, created = Folder.objects.get_or_create(id=pk)
    folder.name = request.POST.get('name','')
    try:
        folder.id_parent_dir =  Folder.objects.get(id=request.POST.get('id_parent_dir', None))
    except Folder.DoesNotExist:
        folder.id_parent_dir = None
    folder.save()
    return JsonResponse({'created': created, 'id': folder.id, 'name': folder.name, 'id_parent_dir': request.POST.get('id_parent_dir', None)})

@login_required()
@api_view(('POST',))
def delete_folder(request, pk = None):
    error = []
    try:
        folder =  get_object_or_404(Folder, pk=pk)
        folder.delete()
        return JsonResponse({'deleted': True})
    except ProtectedError as e:
        for files in e.protected_objects:
            error.append({
                'id': files.id,
                'name': files.name
            })
        return JsonResponse({'deleted': False, 'error': error})

@login_required()
@api_view(('POST',))
def document_delete(request, pk = None):
    file =  get_object_or_404(File, pk=pk)
    OpenIAService().deleteInstance(file)
    file.delete()
    return redirect("documents:list" )

documents/templates/documents/add_edit.html
{% extends "BuscaSemantica/base.html" %}
{% block content %}
{% load controllForms %}
    <div class="p-3 bg-light h-100">
        <div class="d-flex flex-row h-100">
            <div class="card d-flex flex-column flex-shrink-0 h-100" style="margin-right: 10px; width: 280px;">
                {% include "documents/folder-tree/folder-tree.html" with folder_tree=folders %}
            </div>
            <div class="card d-flex flex-column flex-shrink-0 p-3 h-100" style="width: calc(100% - 290px);">
                <div class='d-flex flex-row'>
                    <a class="nav-link" href="{% url 'documents:list' %}"><i class="bi bi-chevron-left" style="font-size: 1.25rem;margin-right:5px"></i></a>
                    <h3>{{form.form_title}}</h3>
                </div>
                <form id='form_document' style="height: calc(100% - 38px);" class=' d-flex flex-column' enctype="multipart/form-data">
                    <!--  -->
                    <div class="overflow-auto border-bottom px-2 h-100" >
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field|input_type == 'HiddenInput' %}
                                {{field}} 
                            {% elif field.name == 'file'  %}
                                <div class="mb-3">
                                    <label for="{{field.name}}" class="form-label">{{field.label}}</label>
                                    {% if form.instance.file %}
                                    
                                    <div class='d-flex flex-row mb-1'>
                                        <i class="bi bi-file-earmark mx-1 text-decoration-none"> </i>
                                        <div class=''>
                                            <span> Documento Atual: </span>
                                            <a class="mx-2" href="/media/{{form.instance.file}}" download> {{form.instance.filename}} </a>
                                            <button type="button" data-bs-toggle="button" id="delete-file" class=" p-0 px-1 btn btn-danger">
                                                <i class="bi bi-trash3"></i>
                                            </button>
                                        </div>
                                    </div>
                                    {% endif %}
                                    <input type="file" accept="application/pdf" name="file" class="form-control" id="id_file">
                                </div>
                            {% else %}
                            <div class="mb-3">
                                <label for="{{field.name}}" class="form-label">{{field.label}}</label>
                                {{field|add_classes:'form-control'}}
                            </div>
                            {% endif %}
                        {% endfor %}
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                {{ form.errors }}
                            </div>
                        {% endif %}
                        <p class="card-text">
                            <small class="text-body-secondary">
                                {% if form.instance.pk %}
                                <i class="bi bi-pencil-fill text-secondary px-2"></i>
                                <span>Criado por {{form.instance.user_created}} em {{form.instance.dt_created}} </span>
                                    {% if form.instance.user_updated %}
                                        <span class='mx-2'>Editado por {{form.instance.user_updated}} em {{form.instance.dt_updated}} </span>
                                    {% endif %}
                                {% endif %}
                            </small>
                        </p>
                    </div>
                    <div class='d-flex flex-row-reverse'>
                        <button type="submit" class="btn mt-2 mx-2 btn-primary">Salvar</button>
                        <!-- <a href="{% url 'documents:add' %}" class="btn btn-light text-nowrap mt-2" tabindex="-1" role="button" aria-disabled="true">Salvar e Novo </a> -->
                        {% if form.instance.pk %}
                        <button type="button" data-bs-toggle="modal" data-bs-target="#delete_document" class="btn mt-2 mx-2 btn-danger">Excluir</button>
                        {% endif %}
                    </div>
                </form>  
            </div>
        </div>
    </div>
    <script>
        
        document.addEventListener('DOMContentLoaded', function() {

            const valueEdit = document.querySelector('select[name="id_folder"]').value;
            window.FolderTree.$element.querySelectorAll(`div[data-id="${valueEdit}"] span`).forEach( element => {
                window.FolderTree.filteredSpan = element;

                element.classList.add('selected');
            })
            window.FolderTree.addEventListener("created_folder", (event) => {
                document.querySelector('select[name="id_folder"]').innerHTML += `<option value="${event.detail.id}">${event.detail.name}</option>`  
            })
            window.FolderTree.addEventListener("span_clicked", (event) => {
                const value = event.detail.id || '';
                document.querySelector('select[name="id_folder"]').value = value;
            });
            window.FolderTree.addEventListener("deleted_folder", (event) => {
                document.querySelector(`select[name="id_folder"] option[value="${event.detail.id}"]`).remove();
            });
        });
        
    </script>

    <div class="modal" tabindex="-1" id="delete_document">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form method="POST" {% if form and form.instance.id %}action="{% url 'documents:delete' form.instance.id %}" {% endif%}>
                    {% csrf_token %}
                    <div class="modal-header">
                        <h5 class="modal-title">Deletar documento</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Deseja realmente excluir este documento? <br>
                        Ele não poderá ser recuperado
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Fechar</button>
                        <button type="submit" class="btn btn-danger">Excluir</button>
                    </div>
                            
                </form>
            </div>
        </div>
    </div>
{% endblock %}

documents/templates/documents/list.html
{% extends "BuscaSemantica/base.html" %}
{% block content %}
{% load controllForms %}

<div class="p-3 bg-light h-100">
    <div class="d-flex flex-row h-100">
        <div class="card d-flex flex-column flex-shrink-0 h-100" style="margin-right: 10px; width: 280px;">
            {% include "documents/folder-tree/folder-tree.html" with folder_tree=folders %}
        </div>
        <div class="card d-flex flex-column flex-shrink-0 p-3 h-100" style="width: calc(100% - 290px);">
            <div class="inner-addon right-addon">
                <i class="bi bi-search"></i>
                <input class="form-control" id="doc-name" type="text" placeholder="Pesquisar documento..." data-sb-validations="required" />
            </div>
            
            <div class='py-2 w-100' id='filter-folder'>
                    
            </div>
            <div class='overflow-auto border' style="height: calc(100% - 38px);">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        {% for column in metadata.columns %}
                            {%if column.attname == 'id' %}
                                <th style="text-align: right">{{column.verbose_name}}</th>
                            {% elif column.attname == 'file' %}
                                <th scope="col" class="text-center">{{column.verbose_name}}</th>
                            {% else %}
                                <th scope="col">{{column.verbose_name}}</th>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                        {% for row in metadata.content %}
                            <tr data-bs-toggle="tooltip" data-bs-placement="top" title="{{ row.name }}">
                                {% for column in metadata.columns %}
                                    {%if column.attname == 'id' %}
                                        <td class='{{column.attname}}' style="text-align: right; width: 70px;">
                                            <a class="nav-link text-primary d-flex flex-row justify-content-end " href="{% url 'documents:edit' row.id %}"> 
                                                <i class="bi bi-pencil-square d-flex  d-none" data-bs-toggle="tooltip" data-bs-placement="top" title="Editar" style='margin-right:10px'></i> 
                                                <span>{{row|get_obj_attr:column.attname}} </span>
                                            </a>
                                        </td>
                                    {% elif column.attname == 'file' %}
                                        
                                        <td class="text-center {{column.attname}}">
                                            {%if row|get_obj_attr:column.attname %}
                                                <a href="/media/{{row|get_obj_attr:column.attname}}" download> 
                                                    <i class="bi bi-filetype-pdf" data-bs-toggle="tooltip" data-bs-placement="top" title="Fazer download do arquivo"></i> 
                                                </a>
                                            {% endif %}
                                            </td>
                                    {% elif column.attname == 'id_folder' %}
                                        <td class='{{column.attname}}' data-id="{{row|get_obj_id:column.attname}}">{{row|get_obj_attr:column.attname}} </td>
                                    {% else %}
                                        <td class='{{column.attname}}'>{{row|get_obj_attr:column.attname}} </td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>  
            </div>  
            <div class="d-flex flex-row  flex-row-reverse pt-2">
                <a href="{% url 'documents:add' %}" class="btn btn-primary text-nowrap" tabindex="-1" role="button" aria-disabled="true"> <i class="bi bi-plus"></i>  <span class="text-nowrap">Incluir documento</span></a>
    
            </div>       
        </div>
    </div>
</div>
<script>
        
    document.addEventListener('DOMContentLoaded', function() {

        window.FolderTree.addEventListener("span_clicked", (eventSpan) => {
            document.querySelector('#filter-folder').innerHTML = '';
            if (event.detail.id){
                const folder = document.createElement('span');
                folder.className = 'badge rounded-pill text-bg-secondary text-white mx-1';
                folder.setAttribute('role','button');
                folder.setAttribute('data-id', event.detail.id);
                folder.textContent = event.detail.span.textContent;
                folder.innerHTML += '<i class="bi bi-x"></i>';
                folder.addEventListener('click', () => {
                    folder.remove();
                    eventSpan.detail.span.classList.remove('selected');
                    window.FolderTree.filteredFolder = null;
                    window.FolderTree.filterDocuments();
                });
                document.querySelector('#filter-folder').appendChild(folder);
                
            }
            window.FolderTree.filterDocuments();
        });
    });
    
</script>
<style>
    tbody tr:hover td .bi-pencil-square{
        display: block !important;
    }
</style>
{% endblock %}